### ISSUE TITLE
Code is not complete 

### ISSUE THREAD

**Issue by jmluu** [brianchmiel/Neural-gradients-are-lognormally-distributed-understanding-sparse-and-quantized-training#1]
will the author add the rest parts ?

**Comment by brianchmiel** [comment]
Which part of the code isn't available? 
I think I uploaded all the code.

**Comment by jmluu** [comment]
The files "utils" and "trainer" can't be found.

**Comment by brianchmiel** [comment]
Sorry - my mistake. Added all the files.
If you encounter any other issue, pls contact me.

**Comment by jmluu** [comment]
Thanks~~

**Comment by jmluu** [comment]
Sorry to bother you again; some files are still absent.
like: the definition of quantizied or pruned models,  and "lowp" .

**Comment by brianchmiel** [comment]
Sorry for it.
I uploaded the lowp module (just run python setup.py develop to install it)

There is any other issue?

**Comment by HaFred** [comment]
> Sorry for it.
> I uploaded the lowp module (just run python setup.py develop to install it)
> 
> There is any other issue?

Hi brian @brianchmiel , it seems to me the code is still incomplete to run even though I installed the lowp. I tired the pruning main.py and it returns:
```
Traceback (most recent call last):
  File "main.py", line 461, in <module>
    main()
  File "main.py", line 196, in main
    main_worker(args,ml_logger)
  File "main.py", line 244, in main_worker
    model = models.__dict__[args.model]
KeyError: 'resnet
```
Could you check if the resnet model is not included? THX
